---

- name: check if profile is already present
  shell:
    cmd: ls /home/{{ local_username }}/.mozilla/firefox/ | grep '.*{{ profile_name}}'
  register: profile_exists
  ignore_errors: true

- name: generate profile
  block:
    - name: create profile
      shell: 
        cmd: firefox -headless -no-remote -CreateProfile "{{ profile_name }}"
    - name: update profile path
      shell:
        cmd: ls /home/{{ local_username }}/.mozilla/firefox/ | grep '.*{{ profile_name}}'
      register: profile_update
    - name: copy user.js config in
      copy:
        dest: /home/{{ local_username }}/.mozilla/firefox/{{ profile_update.stdout }}/user.js
        src: user.js
        mode: 0644
        owner: "{{ local_username }}"
        group: "{{ local_username }}"
  when: profile_exists.rc == 1
