---

- name: create xbps ignore rule
  become: yes
  copy:
    dest: /etc/xbps.d/10-ignore.conf
    content: "ignorepkg=chromium"

- name: install qutebrowser
  community.general.xbps:
    name: 
      - qutebrowser
      - python3-adblock
      - chromium-widevine
    state: present

- name: template in config okk
  block:
    - file:
        path: /home/{{ local_username }}/.config/qutebrowser
        state: directory
        mode: 0755
    - template:
        dest: /home/{{ local_username }}/.config/qutebrowser/config.py
        src: config.py.j2
        mode: 0644
        owner: "{{ local_username }}"
        group: "{{ local_username }}"
