---

- name: install udiskie
  become: yes
  community.general.xbps:
    name: 
      - ntfs-3g
    state: present

- name: install xdg-user-dirs
  become: yes
  community.general.pacman:
    name: xdg-user-dirs
    state: present

- name: update user xdg dirs
  shell:
    cmd: xdg-user-dirs-update

- name: install file manager
  become: yes
  community.general.xbps:
    name:
      - thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - ristretto
      - tumbler
      - xarchiver
      - unzip
      - unrar
      - gvfs
      - gvfs-afc
      - gvfs-mtp
      - gvfs-smb
    state: present
