---

- name: generate hostname
  become: yes
  replace:
    path: /etc/hostname
    regexp: '.*'
    replace: "{{ inventory_hostname }}"

- name: install firewall
  become: yes
  community.general.xbps:
    name: ufw
    state: present

- name: enable firewall service
  become: yes
  block:
    - file:
        src: /etc/sv/ufw
        path: /var/service/ufw
        state: link
    - community.general.runit:
        name: ufw
        state: started

- name: ufw configuration
  become: yes
  block:
    - community.general.ufw:
        state: enabled
        logging: 'on'
    - community.general.ufw:
        policy: deny
        direction: incoming
    - community.general.ufw:
        policy: allow
        direction: outgoing 
    - community.general.ufw:
        rule: allow 
        src: "{{ item }}"
      loop:
        - 127.0.0.1
        - '::1'
  
- name: enable soulseek
  become: yes
  community.general.ufw:
    rule: allow
    name: "soulseek"
    log: true
    state: enabled
    proto: tcp
    port: "2234:2239"
  when: inventory_hostname == "m8"
