---

- name: generate hostname
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: enable firewall
  become: yes
  block:
    - community.general.pacman:
        name: firewalld
        state: present
    - systemd:
        name: firewalld
        enabled: true
        state: started
    - shell:
        cmd: firewall-cmd --set-default-zone=drop

- name: enable some defaults
  become: yes
  firewalld:
    zone: drop
    state: enabled
    permanent: true
    immediate: true
    service: "{{ item }}"
  with_items:
    - dhcpv6-client 
    - mdns
    - ssh
  
- name: enable soulseek
  become: yes
  ansible.posix.firewalld:
    zone: drop
    state: enabled
    immediate: true
    permanent: true
    port: 2234-2239/tcp
  when: inventory_hostname == "m8"

- name: install network manager applet
  become: yes
  community.general.pacman:
    name:
      - network-manager-applet
    state: present

- name: systemd nm-applet unit
  block:
    - copy:
        dest: /home/{{ local_username }}/.config
        src: systemd
        mode: 0644
        owner: "{{ local_username }}"
        group: "{{ local_username }}"
    - systemd:
        scope: user
        enabled: true
        daemon_reload: true
        name: nm-applet
