--- 

- name: sorry no gaming :(
  debug:
    msg: gaming role needs a compelte reimplementation (since i decided to move away from flatpak), with bash scripts to lunch games and download new proton version instead of lutris and protonup
