--- 

- name: ensure flatpak is installed
  become: yes
  community.general.pacman:
    name: flatpak
    state: present

- name: add flathub for user installation
  community.general.flatpak_remote:
    name: hub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: install flatpaks
  community.general.flatpak:
    name:
      - org.winehq.Wine/x86_64/stable-22.08
      - net.lutris.Lutris
      - com.valvesoftware.Steam
      - org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/22.08
      - net.davidotek.pupgui2
    state: present
    method: user
    remote: hub

- name: create games folder
  file:
    path: /home/{{ local_username }}/Games
    state: directory
    mode: 0755

- name: give wine full home directory access
  shell:
    cmd: flatpak override --user --filesystem=home org.winehq.Wine

- name: local wineprefix setup
  block:
    - name: check vn prefix
      shell:
        cmd: ls -a /home/{{ local_username }}/Games | grep 'winevn'
      register: winevn_exists
      ignore_errors: true
    - block:
        - name: wineboot winevn prefix
          shell: 
            cmd: WINEARCH=win32 flatpak run --env="WINEPREFIX=/home/{{ local_username }}/Games/.winevn" --command=wineboot org.winehq.Wine
        - name: winetricks stuff
          shell:
            cmd: WINEARCH=win32 flatpak run --env="WINEPREFIX=/home/{{ local_username }}/Games/.winevn" --command=winetricks org.winehq.Wine -q dotnet35 vcrun2005 vcrun2008 vcrun2010 vcrun2012 vcrun2013 vcrun2015 alldlls=default quartz dxvk
      when: winevn_exists.rc == 1
  when: create_prefix == true

- name: install steam devices
  kewlfft.aur.aur:
    name: steam-devices-git
    state: present
    use: yay
    extra_args: removemake
