---

- name: install logiops
  community.general.xbps:
    name: logiops
    state: present

- name: copy config
  become: yes
  copy:
    dest: /etc/logid.cfg
    src: logid.cfg
    mode: 0644
    owner: root
    group: root

- name: enable service
  become: yes
  block:
    - file:
        path: /var/service/logid
        src: /etc/sv/logid
        state: link
    - community.general.runit:
        name: logid
        state: started
